### ISSUE TITLE
Get Account Detail Error

### ISSUE THREAD

**Issue by VagrantPi** [BOLT-Protocol/TideWallet-Backend#113]
版本：v1.0.0
app 在戳 [Get Account Detail](https://github.com/BOLT-Protocol/TideWallet-Backend/wiki/API-v1#13-get-account-detail)  時回傳錯誤

```json 
{
    "powerby": "TideWallet API 1.0.0",
    "success": false,
    "code": "05000000",
    "message": "DB Error(Cannot read property 'type' of null)",
    "payload": {}
}
```

這邊會發現在 `src/backend/libs/Account.js`  336 行左右的 findCurrency 會是 null（這邊應該要找到東西才對），下面 387 行與 397 行 在使用 findCurrency.type 判斷時會噴錯

**Comment by Luphia** [comment]
API 缺少以下資訊：
- number of external key
- number of internal key

**Comment by Luphia** [comment]
修正於 v1.1.0
