### ISSUE TITLE
List Supported Tokens Error

### ISSUE THREAD

**Issue by Luphia** [BOLT-Protocol/TideWallet-Backend#125]
版本：v1.0.0
1. https://staging.tidewallet.io/api/v1/blockchain/8000025B/token?type=TideWallet
2. https://staging.tidewallet.io/api/v1/blockchain/80000001/token?type=TideWallet
3. Return error code 090000 - unknown error(blockchain id not found)
4. should return empty array

**Comment by VagrantPi** [comment]
https://github.com/BOLT-Protocol/TideWallet-Backend/pull/108/files

修改掉 blockchain_id 時遺漏 DB 舊的沒有刪除，從 `/api/v1/blockchain` 會回傳兩個 ropsten 可發現

移除掉 DB 中的舊 blockchain_id 就解決了
