### ISSUE TITLE
API does not work - gas limit 

### ISSUE THREAD

**Issue by Luphia** [BOLT-Protocol/TideWallet-Backend#128]
版本：v1.0.0
/api/v1/blockchain/:blockchain_id/gas-limit

錯誤訊息：
rpc error(invalid argument 0: json: cannot unmarshal hex string \"0x\" into Go struct field TransactionArgs.nonce of type hexutil.Uint64)

**Comment by Waiting4Ever** [comment]
需要滿足每個input
0x開頭的hex string
value 0x後面不能接0，ex: 0x01 (X)，0x1 (O)

**Comment by Luphia** [comment]
修正於 v1.1.0
