### ISSUE TITLE
Difference between Ropsten and ERC20 token TX fee unit in transaction detail

### ISSUE THREAD

**Issue by Luphia** [BOLT-Protocol/TideWallet-Backend#136]
版本：v1.0.0
Transaction list 與 Transaction detail 資訊中，TX fee 部分為 ETH 部分為 GWei

**Comment by Waiting4Ever** [comment]
目前的fee問題
list Transaction 回覆的fee是find currency的單位，是token就會抓到token的decimal而非eth decimal
transaction detail則是最小單位，並沒做處理。

需求為統一回eth單位的fee

**Comment by Luphia** [comment]
修正於 v1.1.0
