### ISSUE TITLE
TideWallet Core

### ISSUE THREAD

**Issue by Luphia** [BOLT-Protocol/TideWallet-Backend#78]
- [x] 伺服器啟動時須自行產生 HD Wallet 並創建各區塊鏈帳戶
- [x] 新增 API api/v1/system/wallet，回傳各區塊鏈上的錢包地址與餘額

**Comment by VagrantPi** [comment]
tidewallet icon
![app-icon-store](https://user-images.githubusercontent.com/12500724/116849408-4a935580-ac21-11eb-85c0-aad163180024.png)

**Comment by Luphia** [comment]
發佈於 v1.0.0
